spring.application.name=demo

<<<<<<< HEAD
gemini.api.key=AIzaSyCdgwXLhc5BmSXFiGzLPgbZAX6MR-lSjXk
=======
gemini.api.key=

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
>>>>>>> 004cd5f6a154d45d7eb995c0a3b0eb97addf48a8
